### ISSUE TITLE
Remove Edge First-Run in Nexus script

### ISSUE THREAD

**Issue by adilio** [adilio/choco-quickstart-scripts#3]
We are using the new Edge (Chromium) in this setup, as it is a Microsoft product, and thus preferred by our users when setting up Windows Servers.

As such, it would be nice to _not_ have Edge prompt for setup on first-run. This will reduce the number of clicks. Also, these are servers, so the Admins will likely NOT be logging to their Microsoft accounts on the browser.

**Comment by adilio** [comment]
The current `microsoft-edge` package is failing on a Windows Server 2019 VM that doesn't have the latest Windows Updates.

Le Sad. 😦 

Commented on the package page here: http://disq.us/p/2i404k9

Also, @ryanrichter94 will post error here.

I _guess_ we're moving back to `googlechrome`. 🤷🏼‍♂️ 

Adding @JPRuskin and @Windos for visibility.

**Comment by ryanrichter94** [comment]
[microsoft-edge.91.0.864.64.MsiInstall.log](https://github.com/adilio/choco-quickstart-scripts/files/6786779/microsoft-edge.91.0.864.64.MsiInstall.log)
MSI log from 1603 MSI error when trying to install V91.0.864.64 of microsoft-edge package

**Comment by adilio** [comment]
After further discussion, we've come to a compromise.

We'd like to continue with `microsoft-edge` as the preferred browser package, seeing as this _is_ a server, and users would likely prefer a Microsoft product.

If the install of Edge fails (silently, to avoid scary red text), then Chrome should be installed instead.

Code:
```powershell
# Install a non-IE browser for browsing the Nexus web portal.
# Edge sometimes fails install due to latest Windows Updates not being installed.
# In that scenario, Google Chrome is installed instead.
$null = choco install microsoft-edge -y
if ($LASTEXITCODE -eq 1) {
    choco install googlechrome -y
}
else {
$RegArgs = @{
    Path = 'HKLM:\SOFTWARE\Microsoft\Edge\'
    Name = 'HideFirstRunExperience'
    Type = 'Dword'
    Value = 1
    Force = $true
    }
    Set-ItemProperty @RegArgs
}
```
